name: notetaker
description: A note taking flutter application

version: 1.0.0+1

environment:
  sdk: ">=2.10.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  path_provider: ^2.0.1
  image_picker: ^0.7.2
  get: ^3.26.0
  firebase_auth: ^1.0.0
  cloud_firestore: ^1.0.0
  firebase_core: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

